function build_slice_IK()
%BUILD_SLICE_IK Programmatically build FruitSorting_slice.slx.
%   Vertical slice #1: a Constant block feeds a target Cartesian position into
%   a MATLAB Function block that calls the Python IK, and the resulting joint
%   vector is captured with a To Workspace block. Used to prove the
%   Simulink <-> Python bridge before layering on vision, FSM and hardware I/O.

    model = 'FruitSorting_slice';

    if bdIsLoaded(model), close_system(model, 0); end
    mdl_path = fullfile(fileparts(mfilename('fullpath')), [model '.slx']);
    if isfile(mdl_path), delete(mdl_path); end

    new_system(model);
    open_system(model);

    set_param(model, ...
        'Solver', 'FixedStepDiscrete', ...
        'FixedStep', '0.002', ...
        'StopTime', '0.01', ...
        'SaveOutput', 'on', ...
        'SaveFormat', 'Dataset');

    add_block('simulink/Sources/Constant', [model '/Target'], ...
        'Value', '[0.30; -0.20; 0.05]', ...
        'SampleTime', '0.002', ...
        'Position', [30 40 90 80]);

    add_block('simulink/User-Defined Functions/MATLAB Function', ...
        [model '/IK'], ...
        'Position', [160 30 260 90]);

    sf = sfroot;
    chart = sf.find('-isa','Stateflow.EMChart','Path',[model '/IK']);
    chart.Script = sprintf([...
        'function phi = fcn(p)\n' ...
        '%%#codegen\n' ...
        'coder.extrinsic(''py_ik'');\n' ...
        'phi = zeros(4,1);\n' ...
        'tmp = zeros(4,1);\n' ...
        'tmp = py_ik(p);\n' ...
        'phi = double(tmp);\n' ...
        'end\n']);

    add_block('simulink/Sinks/To Workspace', [model '/phi_out'], ...
        'VariableName', 'phi_log', ...
        'SaveFormat', 'Array', ...
        'Position', [330 40 420 80]);

    add_line(model, 'Target/1', 'IK/1', 'autorouting', 'on');
    add_line(model, 'IK/1', 'phi_out/1', 'autorouting', 'on');

    save_system(model, mdl_path);
    fprintf('Built %s\n', mdl_path);
    close_system(model, 0);
end
