function build_slice_fsm()
%BUILD_SLICE_FSM Programmatically build FruitSorting_slice_fsm.slx.
%   Vertical slice #3: closed-loop FSM + IK. A unit-delay holds the
%   previous joint command; each tick it's fed into py_controller, which
%   advances the Python FSM and returns the next joint/gripper command.
%   This is the full pick-and-place pipeline running in Simulink with
%   Python doing the heavy lifting.

    model = 'FruitSorting_slice_fsm';

    if bdIsLoaded(model), close_system(model, 0); end
    mdl_path = fullfile(fileparts(mfilename('fullpath')), [model '.slx']);
    if isfile(mdl_path), delete(mdl_path); end

    new_system(model);
    open_system(model);

    dt = 0.05;   % 20 Hz — fast enough for trajectory tracking, slow
                 % enough that a 30 s sim is 600 extrinsic calls.

    set_param(model, ...
        'Solver', 'FixedStepDiscrete', ...
        'FixedStep', num2str(dt), ...
        'StopTime', '30', ...
        'SaveOutput', 'on', ...
        'SaveFormat', 'Dataset');

    % --- Controller MATLAB Function block ---
    add_block('simulink/User-Defined Functions/MATLAB Function', ...
        [model '/FSM'], 'Position', [180 30 320 150]);

    sf = sfroot;
    chart = sf.find('-isa','Stateflow.EMChart','Path',[model '/FSM']);
    chart.Script = sprintf([...
        'function [phi_cmd, gripper, state_id, done] = fcn(phi_prev, tick)\n' ...
        '%%#codegen\n' ...
        'coder.extrinsic(''py_controller'');\n' ...
        'phi_cmd = zeros(4,1);\n' ...
        'gripper = 0;\n' ...
        'state_id = int32(0);\n' ...
        'done = int32(0);\n' ...
        'reset_flag = double(tick == 0);\n' ...
        '[phi_tmp, g_tmp, s_tmp, d_tmp] = py_controller(phi_prev, %.4f, reset_flag);\n' ...
        'phi_cmd = double(phi_tmp);\n' ...
        'gripper = double(g_tmp);\n' ...
        'state_id = int32(s_tmp);\n' ...
        'done = int32(d_tmp);\n' ...
        'end\n'], dt);

    % --- Tick counter (drives reset) ---
    add_block('simulink/Discrete/Discrete-Time Integrator', ...
        [model '/Tick'], ...
        'gainval', '1', 'SampleTime', num2str(dt), ...
        'Position', [40 140 90 180]);
    add_block('simulink/Sources/Constant', [model '/one'], ...
        'Value', '1', 'SampleTime', num2str(dt), ...
        'Position', [-40 140 10 180]);

    % --- Unit delay feeding phi back to the controller ---
    add_block('simulink/Discrete/Unit Delay', [model '/phi_delay'], ...
        'InitialCondition', '[0;0;0;0]', 'SampleTime', num2str(dt), ...
        'Position', [380 40 430 80]);

    % --- Logging sinks ---
    add_block('simulink/Sinks/To Workspace', [model '/phi_out'], ...
        'VariableName', 'phi_cmd_log', 'SaveFormat', 'Array', ...
        'Position', [470 30 560 70]);
    add_block('simulink/Sinks/To Workspace', [model '/grip_out'], ...
        'VariableName', 'gripper_log', 'SaveFormat', 'Array', ...
        'Position', [470 70 560 110]);
    add_block('simulink/Sinks/To Workspace', [model '/state_out'], ...
        'VariableName', 'state_log', 'SaveFormat', 'Array', ...
        'Position', [470 110 560 150]);
    add_block('simulink/Sinks/To Workspace', [model '/done_out'], ...
        'VariableName', 'done_log', 'SaveFormat', 'Array', ...
        'Position', [470 150 560 190]);

    % --- Wiring ---
    add_line(model, 'one/1',       'Tick/1',  'autorouting', 'on');
    add_line(model, 'Tick/1',      'FSM/2',   'autorouting', 'on');
    add_line(model, 'phi_delay/1', 'FSM/1',   'autorouting', 'on');
    add_line(model, 'FSM/1',       'phi_delay/1', 'autorouting', 'on');
    add_line(model, 'FSM/1',       'phi_out/1',   'autorouting', 'on');
    add_line(model, 'FSM/2',       'grip_out/1',  'autorouting', 'on');
    add_line(model, 'FSM/3',       'state_out/1', 'autorouting', 'on');
    add_line(model, 'FSM/4',       'done_out/1',  'autorouting', 'on');

    save_system(model, mdl_path);
    fprintf('Built %s\n', mdl_path);
    close_system(model, 0);
end
