function build_hardware_model()
%BUILD_HARDWARE_MODEL Top-level FruitSorting_Hardware.slx.
%   FSM (py.sorting_controller_sim) in closed loop with py_qarm_io acting
%   as the QArm facade. Runs in SIMULATE mode by default (no hardware);
%   flipping the `qarm_mode` constant to 1 turns it into the hardware
%   loop for the lab machine once QUARC is installed.

    model = 'FruitSorting_Hardware';

    if bdIsLoaded(model), close_system(model, 0); end
    mdl_path = fullfile(fileparts(mfilename('fullpath')), [model '.slx']);
    if isfile(mdl_path), delete(mdl_path); end

    new_system(model);
    open_system(model);

    dt = 0.05;

    set_param(model, ...
        'Solver', 'FixedStepDiscrete', ...
        'FixedStep', num2str(dt), ...
        'StopTime', '30', ...
        'SaveOutput', 'on', ...
        'SaveFormat', 'Dataset');

    % --- qarm_mode constant (0 = simulate, 1 = hardware) ---
    add_block('simulink/Sources/Constant', [model '/qarm_mode'], ...
        'Value', '0', 'SampleTime', num2str(dt), ...
        'OutDataTypeStr', 'int32', ...
        'Position', [30 240 80 270]);

    % --- Tick counter ---
    add_block('simulink/Sources/Constant', [model '/one'], ...
        'Value', '1', 'SampleTime', num2str(dt), ...
        'Position', [-40 300 0 330]);
    add_block('simulink/Discrete/Discrete-Time Integrator', ...
        [model '/Tick'], 'gainval', '1', 'SampleTime', num2str(dt), ...
        'Position', [30 300 80 330]);

    % --- FSM block ---
    add_block('simulink/User-Defined Functions/MATLAB Function', ...
        [model '/FSM'], 'Position', [160 30 300 170]);
    sf = sfroot;
    fsm_chart = sf.find('-isa','Stateflow.EMChart','Path',[model '/FSM']);
    fsm_chart.Script = sprintf([...
        'function [phi_cmd, gripper, state_id, done] = fcn(joints_fb, tick)\n' ...
        '%%#codegen\n' ...
        'coder.extrinsic(''py_controller'');\n' ...
        'phi_cmd = zeros(4,1);\n' ...
        'gripper = 0;\n' ...
        'state_id = int32(0);\n' ...
        'done = int32(0);\n' ...
        'reset_flag = double(tick == 0);\n' ...
        '[phi_tmp, g_tmp, s_tmp, d_tmp] = py_controller(joints_fb, %.4f, reset_flag);\n' ...
        'phi_cmd = double(phi_tmp);\n' ...
        'gripper = double(g_tmp);\n' ...
        'state_id = int32(s_tmp);\n' ...
        'done = int32(d_tmp);\n' ...
        'end\n'], dt);

    % --- QArm IO block ---
    add_block('simulink/User-Defined Functions/MATLAB Function', ...
        [model '/QArmIO'], 'Position', [380 30 520 170]);
    io_chart = sf.find('-isa','Stateflow.EMChart','Path',[model '/QArmIO']);
    io_chart.Script = sprintf([...
        'function [joints_fb, gripper_fb] = fcn(phi_cmd, gripper_cmd, qmode)\n' ...
        '%%#codegen\n' ...
        'coder.extrinsic(''py_qarm_io'');\n' ...
        'joints_fb = zeros(4,1);\n' ...
        'gripper_fb = 0;\n' ...
        '[jtmp, gtmp] = py_qarm_io(phi_cmd, gripper_cmd, double(qmode));\n' ...
        'joints_fb = double(jtmp);\n' ...
        'gripper_fb = double(gtmp);\n' ...
        'end\n']);

    % --- Feedback delay so the algebraic loop is broken ---
    add_block('simulink/Discrete/Unit Delay', [model '/joints_delay'], ...
        'InitialCondition', '[0;0;0;0]', 'SampleTime', num2str(dt), ...
        'Position', [90 30 140 70]);

    % --- Logging sinks ---
    add_block('simulink/Sinks/To Workspace', [model '/phi_out'], ...
        'VariableName', 'phi_cmd_log', 'SaveFormat', 'Array', ...
        'Position', [570 30 660 70]);
    add_block('simulink/Sinks/To Workspace', [model '/grip_out'], ...
        'VariableName', 'gripper_log', 'SaveFormat', 'Array', ...
        'Position', [570 70 660 110]);
    add_block('simulink/Sinks/To Workspace', [model '/state_out'], ...
        'VariableName', 'state_log', 'SaveFormat', 'Array', ...
        'Position', [570 110 660 150]);
    add_block('simulink/Sinks/To Workspace', [model '/done_out'], ...
        'VariableName', 'done_log', 'SaveFormat', 'Array', ...
        'Position', [570 150 660 190]);
    add_block('simulink/Sinks/To Workspace', [model '/fb_out'], ...
        'VariableName', 'joints_fb_log', 'SaveFormat', 'Array', ...
        'Position', [570 190 660 230]);

    % --- Scope for joints ---
    add_block('simulink/Sinks/Scope', [model '/JointScope'], ...
        'Position', [570 260 620 300]);

    % --- Wiring ---
    add_line(model, 'one/1',           'Tick/1',        'autorouting','on');
    add_line(model, 'joints_delay/1',  'FSM/1',         'autorouting','on');
    add_line(model, 'Tick/1',          'FSM/2',         'autorouting','on');
    add_line(model, 'FSM/1',           'QArmIO/1',      'autorouting','on');
    add_line(model, 'FSM/2',           'QArmIO/2',      'autorouting','on');
    add_line(model, 'qarm_mode/1',     'QArmIO/3',      'autorouting','on');
    add_line(model, 'QArmIO/1',        'joints_delay/1','autorouting','on');
    add_line(model, 'FSM/1',           'phi_out/1',     'autorouting','on');
    add_line(model, 'FSM/2',           'grip_out/1',    'autorouting','on');
    add_line(model, 'FSM/3',           'state_out/1',   'autorouting','on');
    add_line(model, 'FSM/4',           'done_out/1',    'autorouting','on');
    add_line(model, 'QArmIO/1',        'fb_out/1',      'autorouting','on');
    add_line(model, 'QArmIO/1',        'JointScope/1',  'autorouting','on');

    save_system(model, mdl_path);
    fprintf('Built %s\n', mdl_path);
    close_system(model, 0);
end
