function build_slice_vision()
%BUILD_SLICE_VISION Programmatically build FruitSorting_slice_vision.slx.
%   Vertical slice #2: trigger -> MATLAB Function block that calls
%   py_detect_test (which wraps py.fruit_detector.detect_fruits) -> To
%   Workspace logging of detection matrix and count.

    model = 'FruitSorting_slice_vision';

    if bdIsLoaded(model), close_system(model, 0); end
    mdl_path = fullfile(fileparts(mfilename('fullpath')), [model '.slx']);
    if isfile(mdl_path), delete(mdl_path); end

    new_system(model);
    open_system(model);

    set_param(model, ...
        'Solver', 'FixedStepDiscrete', ...
        'FixedStep', '0.1', ...
        'StopTime', '0.1', ...
        'SaveOutput', 'on', ...
        'SaveFormat', 'Dataset');

    add_block('simulink/Sources/Constant', [model '/Trigger'], ...
        'Value', '1', 'SampleTime', '0.1', ...
        'Position', [30 40 80 80]);

    add_block('simulink/User-Defined Functions/MATLAB Function', ...
        [model '/Detect'], ...
        'Position', [140 20 260 100]);

    sf = sfroot;
    chart = sf.find('-isa','Stateflow.EMChart','Path',[model '/Detect']);
    chart.Script = sprintf([...
        'function [det, count] = fcn(trig)\n' ...
        '%%#codegen\n' ...
        'coder.extrinsic(''py_detect_test'');\n' ...
        'det = zeros(8,5);\n' ...
        'count = int32(0);\n' ...
        '[det_tmp, cnt_tmp] = py_detect_test(trig);\n' ...
        'det = double(det_tmp);\n' ...
        'count = int32(cnt_tmp);\n' ...
        'end\n']);

    add_block('simulink/Sinks/To Workspace', [model '/det_out'], ...
        'VariableName', 'det_log', ...
        'SaveFormat', 'Array', ...
        'Position', [320 20 420 60]);

    add_block('simulink/Sinks/To Workspace', [model '/count_out'], ...
        'VariableName', 'count_log', ...
        'SaveFormat', 'Array', ...
        'Position', [320 70 420 110]);

    add_line(model, 'Trigger/1', 'Detect/1', 'autorouting', 'on');
    add_line(model, 'Detect/1', 'det_out/1', 'autorouting', 'on');
    add_line(model, 'Detect/2', 'count_out/1', 'autorouting', 'on');

    save_system(model, mdl_path);
    fprintf('Built %s\n', mdl_path);
    close_system(model, 0);
end
